name: pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^5.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_native_splash: ^2.2.19
  getwidget: ^3.1.1
  material_floating_search_bar_2: ^0.5.0
  custom_navigation_bar: ^0.8.2

flutter_native_splash:
  color: '#000029'
  color_dark: '#000029'
  image: 'lib/assets/images/splash_image.png'
  image_dark: 'lib/assets/images/splash_image.png'
  android_12:
    color: "#000029"
    color_dark: "#000029"
    image: lib/assets/images/splash_image.png
    image_dark: lib/assets/images/splash_image.png
    icon_background_color: "#000029"
    icon_background_color_dark: "#000029"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/
    - lib/assets/json/
